version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "200k"
    max-file: "10"

services:

  proxy:
    volumes:
      - ./optional-components/weaver/conf.extra-service.d:/etc/nginx/conf.extra-service.d/weaver
    links:
      - weaver

  magpie:
    volumes:
      - ./optional-components/weaver/config/magpie/config.yml:/opt/local/src/magpie/config/permissions/weaver-permissions.cfg:ro
      - ./optional-components/weaver/config/magpie/config.yml:/opt/local/src/magpie/config/providers/weaver-provider.cfg:ro

  # add health checks for each WPS provider to ensure they are ready for registration into Weaver
  catalog:
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--insecure"
          "--fail",
          "https://localhost${TWITCHER_PROTECTED_PATH}/catalog?service=WPS&request=GetCapabilities"
        ]
  finch:
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--insecure"
          "--fail",
          "https://localhost${TWITCHER_PROTECTED_PATH}/finch?service=WPS&request=GetCapabilities"
        ]
  flyingpigeon:
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--insecure"
          "--fail",
          "https://localhost${TWITCHER_PROTECTED_PATH}/flyingpigeon?service=WPS&request=GetCapabilities"
        ]
  hummingbird:
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--insecure"
          "--fail",
          "https://localhost${TWITCHER_PROTECTED_PATH}/hummingbird?service=WPS&request=GetCapabilities"
        ]
  malleefowl:
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--insecure"
          "--fail",
          "https://localhost${TWITCHER_PROTECTED_PATH}/malleefowl?service=WPS&request=GetCapabilities"
        ]
  raven:
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--insecure"
          "--fail",
          "https://localhost${TWITCHER_PROTECTED_PATH}/raven?service=WPS&request=GetCapabilities"
        ]

  # FIXME:
  #   Weaver API shouldn't be one doing docker run (jobs), but it is actually the one
  #   running the cwltool app from the received WPS Execute request sent by the worker.
  #   Configs must be moved to the 'worker' with implementation of direct job monitoring.
  #   (https://github.com/crim-ca/weaver/issues/21)
  ${WEAVER_MANAGER_NAME}:
    image: pavics/weaver:${WEAVER_VERSION}-manager
    container_name: ${WEAVER_MANAGER_NAME}
    ports:
      - "4001:4001"
    environment:
      HOSTNAME: ${PAVICS_FQDN}
      FORWARDED_ALLOW_IPS: "*"
      DOCKER_HOST: "tcp://docker-proxy:2375"   # FIXME: see above docker-sibling note
    #env_file:
    #  - ./config/mongodb/credentials.env
    # ensure other referenced services are created beforehand to avoid booting timing issues
    depends_on:
      - catalog
      - finch
      - flyingpigeon
      - hummingbird
      - malleefowl
      - raven
      - ${WEAVER_WORKER_NAME}
    links:
      - mongodb
    volumes:
      - ./optional-components/weaver/config/weaver/weaver.ini:/opt/local/src/weaver/config/weaver.ini
      - ./optional-components/weaver/config/weaver/data_sources.json:/opt/local/src/weaver/config/data_sources.json
      - ./optional-components/weaver/config/weaver/request_options.yml:/opt/local/src/weaver/config/request_options.yml
      - ./optional-components/weaver/config/weaver/wps_processes.yml:/opt/local/src/weaver/config/wps_processes.yml
      - /usr/bin/docker:/usr/bin/docker   # FIXME: see above docker-sibling note
      - ~/.docker/config.json:/root/.docker/config.json   # FIXME: see above docker-sibling note
      # NOTE:
      #   Working and output directories must be mounted as exact same path (e.g.: /tmp/path:/tmp/path)
      #   to avoid mismatching locations between container-side path resolution of cwltool stagedir/tmpdir/outdir
      #   and corresponding server-side runtime docker directories since from the docker application will not be
      #   running inside this docker, but next to it (sibling-dockers).
      - wps_workdir:${WEAVER_WPS_WORKDIR}     # FIXME: with fix WPS-execute inside worker, shouldn't be required anymore
      - wps_outputs:${WEAVER_WPS_OUTPUTS_DIR}
    networks:
      - default
      - docker-proxy  # FIXME: see above docker-sibling note
    restart: always
    logging: *default-logging

  ${WEAVER_WORKER_NAME}:
    image: pavics/weaver:${WEAVER_VERSION}-worker
    container_name: ${WEAVER_WORKER_NAME}
    #env_file:
    #  - ./config/mongodb/credentials.env
    links:
      - mongodb
    volumes:
      #- wps_private:/data/wps_private
      - ${DATA_PERSIST_ROOT}/wps_private:/data/wps_private
      - ./optional-components/weaver/config/weaver/weaver.ini:/opt/local/src/weaver/config/weaver.ini
      - ./optional-components/weaver/config/weaver/request_options.yml:/opt/local/src/weaver/config/request_options.yml
      # NOTE:
      #   Working and output directories must be mounted as exact same path (e.g.: /tmp/path:/tmp/path)
      #   to avoid mismatching locations between container-side path resolution of cwltool stagedir/tmpdir/outdir
      #   and corresponding server-side runtime docker directories since from the docker application will not be
      #   running inside this docker, but next to it (sibling-dockers).
      - wps_workdir:${WEAVER_WPS_WORKDIR}
      - wps_outputs:${WEAVER_WPS_OUTPUTS_DIR}
    restart: always
    logging: *default-logging

  docker-proxy:
    # references
    #   https://github.com/Tecnativa/docker-socket-proxy
    #   https://stackoverflow.com/a/47293798/5936364
    #   https://docs.docker.com/engine/api/
    image: tecnativa/docker-socket-proxy
    container_name: docker-proxy
    environment:
      # DOCKER API permissions
      # These control which operations the docker-proxy allows from other containers
      - SERVICES=0
      - TASKS=0
      - NETWORKS=0
      - NODES=0
      - INFO=1
      - EXEC=1
      - IMAGES=1
      - VOLUMES=1
      - CONTAINERS=1
      - POST=1
    # access to docker for sibling execution
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker-proxy
    logging: *default-logging
    # remote swarm as needed (requires more permissions above)
    #deploy:
    #  placement:
    #    constraints: [node.role == manager]

volumes:
  wps_workdir: {}
#  wps_private:
#    driver_opts:
#      type: none
#      device: ${DATA_PERSIST_ROOT}/wps_private
#      o: bind

networks:
  docker-proxy:
    driver: bridge
